/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbreplicator;

/**
 *
 * @author oscar
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 420, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Base de Datos Origen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 250, 193, 22);

        jLabel4.setText("Puerto");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 360, 100, 16);

        jLabel5.setText("Usuario");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 390, 100, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("           Probar");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 476, 130, 30);

        jLabel7.setText("Nombre Instancia");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 300, 100, 16);

        jLabel8.setText("Nombre BD");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 330, 100, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 330, 110, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(300, 360, 110, 22);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(300, 390, 110, 22);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(300, 420, 110, 22);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(299, 300, 110, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Base de Datos Destino");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(703, 250, 210, 22);

        jLabel10.setText("Nombre Instancia");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(700, 300, 100, 16);

        jLabel11.setText("Nombre BD");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(700, 330, 100, 16);

        jLabel12.setText("Puerto");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(700, 360, 100, 16);

        jLabel13.setText("Usuario");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(700, 390, 100, 20);

        jLabel14.setText("Password");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(700, 420, 70, 30);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(810, 420, 110, 22);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(810, 390, 110, 22);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(810, 360, 110, 22);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(810, 330, 110, 22);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(810, 300, 110, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("           Probar");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(740, 470, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbreplicator/DB.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
